AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scrappy scraper

Resources:
  ScrappyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./Scrappy
    Properties:
      PackageType: Image
      ImageUri: scrappy:latest
      EphemeralStorage:
        Size: 4096
      MemorySize: 2048
      Timeout: 29
      FunctionUrlConfig:
        AuthType: AWS_IAM
  ScrappyNomadPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref ScrappyFunction
      Principal: arn:aws:iam::328601198472:role/laravel-vapor-role

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ScrappyFunction:
    Description: "ScrappyFunction ARN"
    Value: !GetAtt ScrappyFunction.Arn