AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scrappy scraper

Resources:
  ScrappyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./Scrappy
    Properties:
      PackageType: Image
      ImageUri: scrappy:latest
      MemorySize: 1024
      Timeout: 300
      FunctionUrlConfig:
        AuthType: AWS_IAM

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ScrappyApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ScrappyFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt ScrappyFunction.Arn
  ScrappyFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ScrappyFunctionRole.Arn
